version: '3'

services:
  app:
    image: jamshidbekmansurov/zoomify:latest
    container_name: zoomify_app
    restart: always
    ports:
      - '4000:4000'
    env_file:
      - .env
    depends_on:
      - zoomify_postgres
      - zoomify_redis
    volumes:
      - zoomify_sessions:/app/sessions
    networks:
      - zoomify_network

  zoomify_postgres:
    image: postgres:16-alpine
    container_name: zoomify_postgres
    restart: always
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - zoomify_postgres_data:/var/lib/postgresql/data
    networks:
      - zoomify_network

  zoomify_redis:
    image: redis:7.2-alpine
    container_name: zoomify_redis
    restart: always
    ports:
      - '6380:6379'
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - zoomify_redis_data:/data
    networks:
      - zoomify_network

volumes:
  zoomify_postgres_data:
  zoomify_redis_data:
  zoomify_sessions:

networks:
  zoomify_network:
    driver: bridge